#!/usr/bin/perl -w

use strict;
use Nagios::Plugin;
use Nagios::Plugin::Threshold;
use LWP::UserAgent;
use Scalar::Util qw(looks_like_number);

sub print_usage();
sub print_help();

my $PROGNAME = 'check_jrds_values';
my $VERSION = '0.10';

my $np = Nagios::Plugin->new(
  usage => "Usage: %s"
    . '  -H <hostname> -c <threshold> -w <threshold> '
    . ' [-t <timeout>] -U|-L'
    . ' -J <JRDS ROOT URL> -p <Probe instance name> -d <dsName>'
    . ' [-i interval] [-f cfFunction]',
  version => $VERSION,
  plugin  => $PROGNAME,
  shortname => uc($PROGNAME),
  blurb => 'Check a data store value from JRDS',
  timeout => 10,
  license => 'BSD licence'
);

$np->add_arg(
  spec => 'hostname|H=s',
  help => '-H, --hostname=<hostname>',
  required => 1,
);

$np->add_arg(
  spec => 'jrdsurl|J=s',
  help => '-J, --jrdsurl=<JRDS ROOT URL>',
  required => 1,
);

$np->add_arg(
  spec => 'probeinstance|p=s',
  help => '-p, --probeinstancename=<Probe instance name>',
  required => 1,
);

$np->add_arg(
  spec => 'dsname|d=s',
  help => '-d, --dsname=<ds name>',
  required => 1,
);

$np->add_arg(
  spec => 'interval|i=i',
  help => '-i, --interval=<interval (in seconds)>',
  default => 600,
  required => 1,
);

$np->add_arg(
  spec => 'cffunc|f=s',
  help => '-f, --cffunction=<consolidation function>',
  default => 'average',
  required => 0,
);

$np->add_arg(
  spec => 'warning|w=s',
  help => '-w, --warning=value',
  required => 1,
);

$np->add_arg(
  spec => 'critical|c=s',
  help => '-c, --critical=value',
  required => 1,
);

$np->add_arg(
  spec => 'lowerbound|L+',
  help => '-L, --lowerbound',
  required => 0,
  default => 0,
);

$np->add_arg(
  spec => 'upperbound|U+',
  help => '-U, --upperdound',
  required => 0,
  default => 0,
);

$np->getopts;

my $upperbound = $np->opts->upperbound;
my $lowerbound = $np->opts->lowerbound;

if( $upperbound + $lowerbound >= 2) {
    $np->nagios_exit( UNKNOWN, sprintf("Can't give both upper and lower") );
} elsif ($upperbound + $lowerbound == 0) {
    if( $np->opts->warning < $np->opts->critical) {
        $upperbound = 1;
    } else {
        $lowerbound = 1;
    }
}


my $hostname = $np->opts->hostname;
$hostname =~ s/\.prod//;
my $resturl = sprintf("%s/values/%s/%s/%s/%s/%s", $np->opts->jrdsurl, $hostname, $np->opts->probeinstance, $np->opts->dsname, $np->opts->interval, $np->opts->cffunc);

print $resturl;

my $req = HTTP::Request->new(GET =>  $resturl);
my $ua = LWP::UserAgent->new;
$ua->agent("nagios check");
$ua->timeout($np->opts->timeout);


# Check the outcome of the response
my $res = $ua->request($req);
if (! $res->is_success) {
    $np->nagios_exit( UNKNOWN, sprintf("Could not retrieve page because of an HTTP error: %s", $res->status_line) );
}

my $value =  $res->content;
if (! looks_like_number($value)) {
    $np->nagios_exit( CRITICAL, sprintf("invalid value: %s", $value) );
}

my $warn_range;
my $critical_range;

if($upperbound) {
    $warn_range = "@" . $np->opts->warning . ":" . $np->opts->critical;
    $critical_range = "@" . $np->opts->critical . ":";
} elsif($lowerbound) {
    $warn_range = "@" . $np->opts->critical . ":" .  $np->opts->warning;
    $critical_range = "@" . "~:" . $np->opts->critical;
}
print  "\n";
print  $warn_range . "\n";
print  $critical_range . "\n";

my $thresold = Nagios::Plugin::Threshold->new(
        warning  => $warn_range,
        critical => $critical_range,
    );

my $code = $thresold->get_status($value);

if($code != OK) {
    $main::message = "Threshold check failed";
}
else {
    $main::message = "Everything's fine"
}
$np->nagios_exit( $code, sprintf("%s: %0.2f", $main::message, $value) );
